# Generated by Django 2.2.17 on 2021-01-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date'),
        ),
        migrations.AddField(
            model_name='vote',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='last modified'),
        ),
    ]
